name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Conditional Node.js setup ---
      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your node version
        if: ${{ contains(join(steps.*.outcome, ','), 'success') && (github.event_name == 'push') && (contains(github.event.commits[0].message, 'package.json') || contains(github.event.commits[0].message, 'package-lock.json')) }}

      - name: Install dependencies (if needed)
        run: npm install
        if: ${{ contains(join(steps.*.outcome, ','), 'success') && (github.event_name == 'push') && (contains(github.event.commits[0].message, 'package.json') || contains(github.event.commits[0].message, 'package-lock.json')) }}

      - name: Build (if needed)
        run: npm run build # or your build command
        if: ${{ contains(join(steps.*.outcome, ','), 'success') && (github.event_name == 'push') && (contains(github.event.commits[0].message, 'package.json') || contains(github.event.commits[0].message, 'package-lock.json')) }}
      # --- End conditional Node.js setup ---

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # or your build folder. If not using node.js, change this to the directory containing your html files. for example './'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
